### ISSUE TITLE
Use output of check_qmd_renders() to create issue on GitHub

### ISSUE THREAD

**Issue by larnsce** [rundel/checklist#1]
Hi @rundel, thank you for working on these great packages that support teaching version control with Git and GitHub. I really enjoy using the ghclass package and for my next class had hoped to combine it with `check_qmd_renders()` from `checklist` to automate some of the homework feedback for a class of 200 students.

## Feature request

I would like to use the output of `check_qmd_renders()` to create an issue, which either tells the student to fix it if it doesn't render. 

Example:

```
if (!check_qmd_renders("path/to/file.qmd")) {
  # If the QMD file does not render correctly, open an issue on GitHub
  issue_create("owner/repo", "QMD file does not render correctly", "The QMD file at path/to/file.qmd does not render correctly.")
}
```

However, I don't get any output from `check_qmd_renders()`, so the above doesn't work.

How could I implement this?

**Comment by rundel** [comment]
Happy to hear that the package is helpful for you - I've just taken a quick stab at this and not sure if it is the right solution but I think it should work. 

I've just pushed a new version to github that includes the `handle_error()` function which is essentially a wrapper around tryCatch(), your usage example would look like the following:

```r
handle_error(
  check_qmd_renders("path/to/file.qmd"),
  on_error = {
    issue_create("owner/repo", "QMD file does not render correctly", "The QMD file at path/to/file.qmd does not render correctly.")
  }
)
```

Try it out and let me know if it works or not for you.

**Comment by larnsce** [comment]
Thank you for the quick implementation. It does work, but I receive this error: 

```
Error in handle_error(check_qmd_renders("test-render-error.qmd"), on_error = {: object 'res' not found
```

I have prepared a reprex from this repo: https://github.com/ghe-learn/check-qmd-render-test

``` r
library(checklist)
library(ghclass)

packageVersion("checklist")
#> [1] '0.1.1'
packageVersion("ghclass")
#> [1] '0.3.0'


# file with error ---------------------------------------------------------

handle_error(
  check_qmd_renders("test-render-error.qmd"),
  on_error = {
    issue_create("ghe-learn/check-qmd-render-test",
                 "The .qmd file does not render correctly",
                 "The .qmd file does not render correctly.
                 Please try to fix the errors and reach out to @larnsce for support.")
  })
#> ✔ Created issue "The .qmd file does not render correctly" for repo "ghe-learn/check-qmd-render-test".
#> Error in handle_error(check_qmd_renders("test-render-error.qmd"), on_error = {: object 'res' not found
```

<sup>Created on 2023-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rundel** [comment]
Thats what I get for trying to be clever at the last moment - it should be fixed now with some additional basic tests added. Let me know if it works for you now.

**Comment by larnsce** [comment]
Thanks, @rundel. It works exactly as I had hoped. I appreciate your efforts.
